version: '3'
services:
  app:
    build: .
    working_dir: /app
    volumes:
    - .:/app
    - bundle:/bundle
    command: ['bundle', 'exec', 'rackup', '-o', '0.0.0.0']
    ports:
    - 9292:9292
volumes:
  bundle:
    driver: local
